server:
  port: 9002
spring:
  application:
    name: microservice-movie
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka # http://localhost:9999/eureka
  instance:
    prefer-ip-address: true
#microservice-user:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true